<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            ['category_id' => 1, 'name' => 'Tôm sú tươi sống', 'slug' => 'tom-su-tuoi-song', 'price' => 350000, 'original_price' => 420000, 'description' => 'Tôm sú tươi sống, size lớn 15-20 con/kg. Thịt chắc, ngọt tự nhiên, được đánh bắt từ vùng biển Cà Mau. Phù hợp hấp, nướng, rang muối.', 'origin' => 'Cà Mau, Việt Nam', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => true, 'is_new' => false, 'stock' => 50, 'rating' => 4.8],
            ['category_id' => 1, 'name' => 'Tôm thẻ chân trắng', 'slug' => 'tom-the-chan-trang', 'price' => 180000, 'original_price' => 220000, 'description' => 'Tôm thẻ chân trắng tươi, size 30-40 con/kg. Nuôi theo công nghệ sạch, đảm bảo vệ sinh an toàn thực phẩm.', 'origin' => 'Bạc Liêu, Việt Nam', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => true, 'is_new' => false, 'stock' => 80, 'rating' => 4.5],
            ['category_id' => 1, 'name' => 'Tôm hùm bông', 'slug' => 'tom-hum-bong', 'price' => 1200000, 'original_price' => 1500000, 'description' => 'Tôm hùm bông tươi sống, size 500g-800g/con. Thịt dai ngọt, chắc nịch. Món quà biển cao cấp.', 'origin' => 'Phú Yên, Việt Nam', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => true, 'is_new' => false, 'stock' => 15, 'rating' => 4.9],
            ['category_id' => 1, 'name' => 'Tôm tích đông lạnh', 'slug' => 'tom-tich-dong-lanh', 'price' => 250000, 'original_price' => 300000, 'description' => 'Tôm tích đông lạnh, bóc vỏ sẵn, tiện lợi chế biến. Đóng gói hút chân không.', 'origin' => 'Khánh Hòa, Việt Nam', 'weight' => '500g', 'unit' => 'gói', 'type' => 'frozen', 'is_best_seller' => false, 'is_new' => true, 'stock' => 60, 'rating' => 4.3],
            ['category_id' => 1, 'name' => 'Tôm mũ ni', 'slug' => 'tom-mu-ni', 'price' => 450000, 'original_price' => 550000, 'description' => 'Tôm mũ ni tươi sống, size lớn. Vỏ dày, thịt nhiều, vị ngọt đậm đà.', 'origin' => 'Phan Thiết, Việt Nam', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => false, 'is_new' => true, 'stock' => 25, 'rating' => 4.6],

            ['category_id' => 2, 'name' => 'Cá hồi Na Uy nguyên con', 'slug' => 'ca-hoi-na-uy-nguyen-con', 'price' => 580000, 'original_price' => 680000, 'description' => 'Cá hồi Na Uy nhập khẩu nguyên con, thịt cam đẹp, béo ngậy. Thích hợp làm sashimi, nướng, áp chảo.', 'origin' => 'Na Uy', 'weight' => '2-3kg/con', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => true, 'is_new' => false, 'stock' => 20, 'rating' => 4.9],
            ['category_id' => 2, 'name' => 'Cá chẽm biển', 'slug' => 'ca-chem-bien', 'price' => 160000, 'original_price' => 190000, 'description' => 'Cá chẽm biển tươi sống, thịt trắng dai ngọt. Phù hợp hấp, nấu canh, chiên giòn.', 'origin' => 'Vũng Tàu, Việt Nam', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => false, 'is_new' => false, 'stock' => 40, 'rating' => 4.4],
            ['category_id' => 2, 'name' => 'Cá ngừ đại dương', 'slug' => 'ca-ngu-dai-duong', 'price' => 280000, 'original_price' => 350000, 'description' => 'Cá ngừ đại dương cắt lát, thịt đỏ tươi, giàu omega-3. Làm sashimi, bò nê tuyệt vời.', 'origin' => 'Bình Định, Việt Nam', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => true, 'is_new' => false, 'stock' => 30, 'rating' => 4.7],
            ['category_id' => 2, 'name' => 'Cá mú đỏ', 'slug' => 'ca-mu-do', 'price' => 420000, 'original_price' => 500000, 'description' => 'Cá mú đỏ tươi sống, thịt chắc ngọt, ít xương. Hấp Hồng Kông, nấu lẩu cực ngon.', 'origin' => 'Nha Trang, Việt Nam', 'weight' => '1-2kg/con', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => false, 'is_new' => true, 'stock' => 18, 'rating' => 4.6],

            ['category_id' => 3, 'name' => 'Cua thịt Cà Mau', 'slug' => 'cua-thit-ca-mau', 'price' => 650000, 'original_price' => 780000, 'description' => 'Cua thịt Cà Mau loại 1, gạch đầy, thịt chắc. Hấp bia, rang me, nướng muối ớt.', 'origin' => 'Cà Mau, Việt Nam', 'weight' => '1kg (2-3 con)', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => true, 'is_new' => false, 'stock' => 25, 'rating' => 4.8],
            ['category_id' => 3, 'name' => 'Ghẹ xanh', 'slug' => 'ghe-xanh', 'price' => 380000, 'original_price' => 450000, 'description' => 'Ghẹ xanh tươi sống, thịt ngọt tự nhiên, gạch béo. Hấp sả, rang muối tuyệt hảo.', 'origin' => 'Kiên Giang, Việt Nam', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => false, 'is_new' => false, 'stock' => 35, 'rating' => 4.5],
            ['category_id' => 3, 'name' => 'Cua Hoàng Đế Alaska', 'slug' => 'cua-hoang-de-alaska', 'price' => 2500000, 'original_price' => 3000000, 'description' => 'Cua Hoàng Đế Alaska nhập khẩu, size king 2-3kg/con. Thịt cua dai ngọt, thơm béo.', 'origin' => 'Alaska, Mỹ', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'frozen', 'is_best_seller' => true, 'is_new' => false, 'stock' => 8, 'rating' => 5.0],

            ['category_id' => 4, 'name' => 'Mực ống tươi', 'slug' => 'muc-ong-tuoi', 'price' => 220000, 'original_price' => 280000, 'description' => 'Mực ống tươi sống, thân dài 15-20cm. Thịt giòn ngọt, nướng sa tế, xào chua ngọt.', 'origin' => 'Phan Thiết, Việt Nam', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => false, 'is_new' => false, 'stock' => 45, 'rating' => 4.4],
            ['category_id' => 4, 'name' => 'Bạch tuộc baby', 'slug' => 'bach-tuoc-baby', 'price' => 190000, 'original_price' => 240000, 'description' => 'Bạch tuộc baby tươi ngon, size nhỏ vừa ăn. Nướng, xào, hấp đều ngon.', 'origin' => 'Quảng Ninh, Việt Nam', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => false, 'is_new' => true, 'stock' => 38, 'rating' => 4.3],
            ['category_id' => 4, 'name' => 'Mực lá tươi', 'slug' => 'muc-la-tuoi', 'price' => 320000, 'original_price' => 380000, 'description' => 'Mực lá tươi sống, thân rộng, thịt dày. Phù hợp nướng, hấp, làm gỏi.', 'origin' => 'Đà Nẵng, Việt Nam', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => true, 'is_new' => false, 'stock' => 28, 'rating' => 4.6],

            ['category_id' => 5, 'name' => 'Sò điệp Hokkaido', 'slug' => 'so-diep-hokkaido', 'price' => 450000, 'original_price' => 550000, 'description' => 'Sò điệp Hokkaido Nhật Bản, size lớn 8-10 con/kg. Thịt ngọt lịm, nướng bơ tỏi cực phẩm.', 'origin' => 'Hokkaido, Nhật Bản', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'frozen', 'is_best_seller' => true, 'is_new' => false, 'stock' => 22, 'rating' => 4.9],
            ['category_id' => 5, 'name' => 'Ốc hương', 'slug' => 'oc-huong', 'price' => 350000, 'original_price' => 420000, 'description' => 'Ốc hương tươi sống, size đều đẹp. Luộc sả, nướng mỡ hành thơm ngất ngây.', 'origin' => 'Phú Quốc, Việt Nam', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => true, 'is_new' => false, 'stock' => 32, 'rating' => 4.7],
            ['category_id' => 5, 'name' => 'Nghêu lụa', 'slug' => 'ngheu-lua', 'price' => 85000, 'original_price' => 100000, 'description' => 'Nghêu lụa tươi, vỏ mỏng thịt ngọt. Xào tỏi, nấu canh chua đều ngon.', 'origin' => 'Bến Tre, Việt Nam', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => false, 'is_new' => false, 'stock' => 70, 'rating' => 4.2],

            ['category_id' => 6, 'name' => 'Hàu sữa Vân Đồn', 'slug' => 'hau-sua-van-don', 'price' => 180000, 'original_price' => 220000, 'description' => 'Hàu sữa Vân Đồn tươi sống, béo ngậy, giàu kẽm. Nướng phô mai, ăn sống đều tuyệt.', 'origin' => 'Quảng Ninh, Việt Nam', 'weight' => '1kg (8-12 con)', 'unit' => 'kg', 'type' => 'fresh', 'is_best_seller' => false, 'is_new' => true, 'stock' => 40, 'rating' => 4.6],
            ['category_id' => 6, 'name' => 'Bào ngư đông lạnh', 'slug' => 'bao-ngu-dong-lanh', 'price' => 750000, 'original_price' => 900000, 'description' => 'Bào ngư Chile đông lạnh, thịt giòn dai, hầm thuốc bắc bổ dưỡng.', 'origin' => 'Chile', 'weight' => '500g (6-8 con)', 'unit' => 'gói', 'type' => 'frozen', 'is_best_seller' => false, 'is_new' => false, 'stock' => 12, 'rating' => 4.8],

            ['category_id' => 7, 'name' => 'Tôm hùm Alaska', 'slug' => 'tom-hum-alaska', 'price' => 1800000, 'original_price' => 2200000, 'description' => 'Tôm hùm Alaska nhập khẩu, size 500-700g/con. Thịt dai ngọt đậm đà.', 'origin' => 'Alaska, Mỹ', 'weight' => '1kg', 'unit' => 'kg', 'type' => 'frozen', 'is_best_seller' => true, 'is_new' => false, 'stock' => 10, 'rating' => 4.9],
            ['category_id' => 7, 'name' => 'Cá hồi sashimi cắt lát', 'slug' => 'ca-hoi-sashimi-cat-lat', 'price' => 380000, 'original_price' => 450000, 'description' => 'Cá hồi Na Uy cắt lát sashimi, đóng gói hút chân không. Ăn kèm wasabi và nước tương.', 'origin' => 'Na Uy', 'weight' => '300g', 'unit' => 'hộp', 'type' => 'fresh', 'is_best_seller' => true, 'is_new' => true, 'stock' => 25, 'rating' => 4.8],
            ['category_id' => 7, 'name' => 'Set hải sản cao cấp BBQ', 'slug' => 'set-hai-san-cao-cap-bbq', 'price' => 1500000, 'original_price' => 1800000, 'description' => 'Set hải sản BBQ gồm: Tôm hùm, sò điệp, cua, ghẹ, mực. Phù hợp tiệc 4-6 người.', 'origin' => 'Tổng hợp', 'weight' => '3kg', 'unit' => 'set', 'type' => 'fresh', 'is_best_seller' => true, 'is_new' => true, 'stock' => 10, 'rating' => 5.0],

            ['category_id' => 8, 'name' => 'Khô mực rim me', 'slug' => 'kho-muc-rim-me', 'price' => 280000, 'original_price' => 350000, 'description' => 'Khô mực rim me chua ngọt, giòn rụm. Snack nhậu lai rai tuyệt đỉnh.', 'origin' => 'Phan Thiết, Việt Nam', 'weight' => '250g', 'unit' => 'gói', 'type' => 'dried', 'is_best_seller' => false, 'is_new' => false, 'stock' => 55, 'rating' => 4.5],
            ['category_id' => 8, 'name' => 'Tôm khô Cà Mau', 'slug' => 'tom-kho-ca-mau', 'price' => 650000, 'original_price' => 800000, 'description' => 'Tôm khô Cà Mau loại 1, size lớn, phơi nắng tự nhiên. Ăn kèm bánh tráng, cuốn gỏi.', 'origin' => 'Cà Mau, Việt Nam', 'weight' => '500g', 'unit' => 'gói', 'type' => 'dried', 'is_best_seller' => true, 'is_new' => false, 'stock' => 30, 'rating' => 4.7],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
